### ISSUE TITLE
Flow Launcher got an error - immediately crash

### ISSUE THREAD

**Issue by CyRamos** [cenyG/flow-launch-translate-plugin#2]
Log has been added to this ticket down below.

Exception message:

> Flow Launcher version: 1.9.3

>OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

>Python Path: 
Date: 10/23/2022 03:33:45
Exception:
System.IO.InvalidDataException: Translation|'node' is not recognized as an internal or external command,
operable program or batch file.

>   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

Many thanks ahead.

[2022-10-23.txt](https://github.com/cenyG/flow-launch-translate-plugin/files/9845496/2022-10-23.txt)

**Comment by cenyG** [comment]
@CyRamos do you have Nodejs instaled ?

**Comment by CyRamos** [comment]
> @CyRamos do you have Nodejs instaled ?

Actually not, do I need a specific version or just install the last version?

**Comment by cenyG** [comment]
@CyRamos should work with latest

**Comment by CyRamos** [comment]
Working. 
Thank you.
